### ISSUE TITLE
Common implementation for JWT based heartbeat auth for srcman

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/discovery#361]
* based on the work in https://github.com/overmindtech/discovery/issues/360, add support for `SOURCE_ACCESS_TOKEN` (string), `SOURCE_TOKEN_TYPE` (string), and `OVERMIND_MANAGED_SOURCE` (bool, hidden) with appropriate descriptions to receive the config from https://github.com/overmindtech/srcman/issues/296
* extend the `EngineConfigFromViper` method to create a `natsTokenClient` like https://github.com/overmindtech/aws-source/blob/7788d00d18d2394548f92969e98ffe2db09d4621/cmd/root.go#L128-L153 does and configure that as `HeartbeatOptions.ManagementClient`. Using either the api key as already implement or the provided access token in a static token source (see `sdp-go/auth/auth.go#NewOAuthTokenClientWithContext`).
* update and deploy aws-source with this version for testing
* tag new version of discovery library
* update all sources to the new version and clean up engine setup code to use the new way
  * [ ] aws-source
  * [ ] k8s-source
  * [ ] stdlib-source
* deploy all of the above to dogfood and test authentication using this method
  - https://ui.honeycomb.io/overmind/environments/test/datasets/aws-source/result/5KNcLd3CD1P should show calls from the managed aws-sources in the dogfood EKS cluster to the df api-server
* deploy to prod

**Comment by tphoney** [comment]
tested with nats keys, adds the source, but does not show in listallsourcesstatus
tested with an api-key and it works too
testing with m2m key

**Comment by tphoney** [comment]
order of merge, 

1. discovery pr, to make the sources green. @tphoney to X4 check today that nats auth works. so we dont break razorpay
2. merge the sources pr's
3. merge the srcman pr, to inject the env vars for m2m tokens

@dylanratcliffe @DavidS-ovm
