### ISSUE TITLE
Remove all of the auto-discovery stuff from discovery

### ISSUE THREAD

**Issue by getinnocuous** [overmindtech/discovery#401]
> This has been implemented here: 
> https://github.com/overmindtech/sdp/blob/main/account.proto#L64-L65

> Next tasks are:

> * [x] Switch over to using this API in the frontend to pre-populate the available types
> * [ ] Remove all of the auto-discovery stuff from `sdp-js` (TODO CREATE TICKET)
> * [ ] Remove all of the auto-discovery stuff from `discovery`, this means getting rid of 
> those meta-types for `overmind-type` etc. (TODO CREATE TICKET)

_Originally posted by @dylanratcliffe in https://github.com/overmindtech/frontend/issues/1564#issuecomment-2513972283_

**Comment by getinnocuous** [comment]
> Here are the adapters that back the functionality in `sdp-js`, these should be able to be comppletely deleted: https://github.com/overmindtech/discovery/blob/main/meta_adapters.go

@dylanratcliffe [Tests are currently failing](https://github.com/overmindtech/discovery/actions/runs/12295207293/job/34311609130) due to `adapterhost.go` not having access to `TypeAdapter`. Is this safe to remove too?

**Comment by dylanratcliffe** [comment]
Yeah the compiler is helping you there, you'll need to find all of the locations that `SourcesAdapter` and `TypeAdapter` are used, understand what they do and remove them, and then repeat for anything that relies on those things etc. I'm available for a rundown in Monks if required
